#ifndef QPROXYMODELLOG_H
#define QPROXYMODELLOG_H

#include <QDebug>

#define QPROXYMODELLOG_LEVEL_TRACE 0
#define QPROXYMODELLOG_LEVEL_DEBUG 1
#define QPROXYMODELLOG_LEVEL_INFO 2
#define QPROXYMODELLOG_LEVEL_WARNING 3
#define QPROXYMODELLOG_LEVEL_CRITICAL 4

#define QPROXYMODELLOG_MIN_LEVEL QPROXYMODELLOG_LEVEL_INFO

#define QPROXYMODELLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""QPROXYMODEL").debug

#define QPROXYMODELLOG_TRACE \
    if(QPROXYMODELLOG_MIN_LEVEL>QPROXYMODELLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""QPROXYMODEL").debug
#define QPROXYMODELLOG_DEBUG \
    if(QPROXYMODELLOG_MIN_LEVEL>QPROXYMODELLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QPROXYMODEL").debug
#define QPROXYMODELLOG_INFO \
    if(QPROXYMODELLOG_MIN_LEVEL>QPROXYMODELLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QPROXYMODEL").info
#define QPROXYMODELLOG_WARNING \
    if(QPROXYMODELLOG_MIN_LEVEL>QPROXYMODELLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QPROXYMODEL").warning
#define QPROXYMODELLOG_CRITICAL \
    if(QPROXYMODELLOG_MIN_LEVEL>QPROXYMODELLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QPROXYMODEL").critical
#define QPROXYMODELLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QPROXYMODEL").fatal

#endif // QPROXYMODELLOG_H
