#ifndef POPUP_LOG_H
#define POPUP_LOG_H

#define POPUPLOG_LEVEL_TRACE 0
#define POPUPLOG_LEVEL_DEBUG 1
#define POPUPLOG_LEVEL_INFO 2
#define POPUPLOG_LEVEL_WARNING 3
#define POPUPLOG_LEVEL_CRITICAL 4

#define POPUPLOG_MIN_LEVEL POPUPLOG_LEVEL_DEBUG

#define POPUPLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""POPUP").debug

#define POPUPLOG_TRACE \
    if(POPUPLOG_MIN_LEVEL>POPUPLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""POPUP").debug
#define POPUPLOG_DEBUG \
    if(POPUPLOG_MIN_LEVEL>POPUPLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"POPUP").debug
#define POPUPLOG_INFO \
    if(POPUPLOG_MIN_LEVEL>POPUPLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"POPUP").info
#define POPUPLOG_WARNING \
    if(POPUPLOG_MIN_LEVEL>POPUPLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"POPUP").warning
#define POPUPLOG_CRITICAL \
    if(POPUPLOG_MIN_LEVEL>POPUPLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"POPUP").critical
#define POPUPLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"POPUP").fatal

#endif // POPUP_LOG_H
