#ifndef QMODELSLOG_H
#define QMODELSLOG_H

#include <QDebug>

#define QMODELSLOG_LEVEL_TRACE 0
#define QMODELSLOG_LEVEL_DEBUG 1
#define QMODELSLOG_LEVEL_INFO 2
#define QMODELSLOG_LEVEL_WARNING 3
#define QMODELSLOG_LEVEL_CRITICAL 4

#define QMODELSLOG_MIN_LEVEL QMODELSLOG_LEVEL_INFO

#define QMODELSLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""QMODELS").debug

#define QMODELSLOG_TRACE \
    if(QMODELSLOG_MIN_LEVEL>QMODELSLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""QMODELS").debug
#define QMODELSLOG_DEBUG \
    if(QMODELSLOG_MIN_LEVEL>QMODELSLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").debug
#define QMODELSLOG_INFO \
    if(QMODELSLOG_MIN_LEVEL>QMODELSLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").info
#define QMODELSLOG_WARNING \
    if(QMODELSLOG_MIN_LEVEL>QMODELSLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").warning
#define QMODELSLOG_CRITICAL \
    if(QMODELSLOG_MIN_LEVEL>QMODELSLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").critical
#define QMODELSLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"QMODELS").fatal

#endif // QMODELSLOG_H
