#ifndef STEP_LOG_H
#define STEP_LOG_H

#define STEPLOG_LEVEL_TRACE 0
#define STEPLOG_LEVEL_DEBUG 1
#define STEPLOG_LEVEL_INFO 2
#define STEPLOG_LEVEL_WARNING 3
#define STEPLOG_LEVEL_CRITICAL 4

#define STEPLOG_MIN_LEVEL STEPLOG_LEVEL_INFO

#define STEPLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""STEP").debug

#define STEPLOG_TRACE \
    if(STEPLOG_MIN_LEVEL>STEPLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""STEP").debug
#define STEPLOG_DEBUG \
    if(STEPLOG_MIN_LEVEL>STEPLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"STEP").debug
#define STEPLOG_INFO \
    if(STEPLOG_MIN_LEVEL>STEPLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"STEP").info
#define STEPLOG_WARNING \
    if(STEPLOG_MIN_LEVEL>STEPLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"STEP").warning
#define STEPLOG_CRITICAL \
    if(STEPLOG_MIN_LEVEL>STEPLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"STEP").critical
#define STEPLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"STEP").fatal

#endif // STEP_LOG_H
