#ifndef GRAPH_LOG_H
#define GRAPH_LOG_H

#define GRAPHLOG_LEVEL_TRACE 0
#define GRAPHLOG_LEVEL_DEBUG 1
#define GRAPHLOG_LEVEL_INFO 2
#define GRAPHLOG_LEVEL_WARNING 3
#define GRAPHLOG_LEVEL_CRITICAL 4

#define GRAPHLOG_MIN_LEVEL GRAPHLOG_LEVEL_INFO

#define GRAPHLOG_NOTICE \
QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1C""GRAPH").debug

#define GRAPHLOG_TRACE \
    if(GRAPHLOG_MIN_LEVEL>GRAPHLOG_LEVEL_TRACE) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"\x1B""GRAPH").debug
#define GRAPHLOG_DEBUG \
    if(GRAPHLOG_MIN_LEVEL>GRAPHLOG_LEVEL_DEBUG) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"GRAPH").debug
#define GRAPHLOG_INFO \
    if(GRAPHLOG_MIN_LEVEL>GRAPHLOG_LEVEL_INFO) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"GRAPH").info
#define GRAPHLOG_WARNING \
    if(GRAPHLOG_MIN_LEVEL>GRAPHLOG_LEVEL_WARNING) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"GRAPH").warning
#define GRAPHLOG_CRITICAL \
    if(GRAPHLOG_MIN_LEVEL>GRAPHLOG_LEVEL_CRITICAL) {} \
    else QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"GRAPH").critical
#define GRAPHLOG_FATAL \
    QMessageLogger(QT_MESSAGELOG_FILE, QT_MESSAGELOG_LINE, QT_MESSAGELOG_FUNC,"GRAPH").fatal

#endif // GRAPH_LOG_H
