
string( TOLOWER "${CMAKE_TOOLCHAIN_FILE}" CMAKE_TOOLCHAIN_FILE_lower )

if(CMAKE_TOOLCHAIN_FILE_lower MATCHES "boot2qt")
    set(BOOT2QT ON)
endif()

if(NOT BOOT2QT)
    set(BOOT2QT OFF)
endif()

if(CMAKE_TOOLCHAIN_FILE_lower MATCHES "raspberrypi4")
    set(RASPBERRY_PI4 ON)
endif()

if(NOT RASPBERRY_PI4)
    set(RASPBERRY_PI4 OFF)
endif()

if(CMAKE_TOOLCHAIN_FILE_lower MATCHES "apalis-imx8")
    set(APALIS_IMX8 ON)
endif()

if(NOT APALIS_IMX8)
    set(APALIS_IMX8 OFF)
endif()

set(BOOT2QT ${BOOT2QT} CACHE STRING "")
set(RASPBERRY_PI4 ${RASPBERRY_PI4} CACHE STRING "")
set(APALIS_IMX8 ${APALIS_IMX8} CACHE STRING "")
