# This file sets some options to control GraphViz graphs.

SET(GRAPHVIZ_CUSTOM_TARGETS TRUE)
# set(GRAPHVIZ_EXTERNAL_LIBS FALSE)
# set(GRAPHVIZ_STATIC_LIBS FALSE)
# set(GRAPHVIZ_SHARED_LIBS FALSE)
set(GRAPHVIZ_MODULE_LIBS FALSE)
# set(GRAPHVIZ_EXECUTABLES FALSE)
